remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Calorie Analysis for popular recipes on foods.com]
description: [Project for EECS 398 at UM]